name: tawk
description: "Modern Flutter plugin for Tawk.to live chat integration. Optimized cross-platform support with efficient DOM injection on web and native WebView on mobile/desktop."
version: 0.1.0
homepage: https://github.com/csertant/tawk
documentation: https://github.com/csertant/tawk#readme
maintainers: 
  - 'Tamas Csertan <tamas@binarybush.dev>'
  - 'Mark Sarvari <mark@binarybush.dev>'
repository: https://github.com/csertant/tawk
issue_tracker: https://github.com/csertant/tawk/issues
license: GPL-3.0-or-later

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        package: dev.binarybush.tawk
        pluginClass: TawkPlugin
      ios:
        pluginClass: TawkPlugin
      web:
        pluginClass: TawkWeb
        fileName: tawk_web.dart
