name: tawk
description: "A small Flutter plugin that embeds tawk.to chat in your app. Supports web (DOM injection) and mobile/desktop via WebView."
version: 0.1.0
homepage: https://github.com/csertant/tawk
documentation: https://github.com/csertant/tawk#readme
maintainers: ['Tamas Csertan <tamas@binarybush.dev>']
repository: https://github.com/csertant/tawk
issue_tracker: https://github.com/csertant/tawk/issues
license: GPL-3.0-or-later

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  webview_flutter: ^4.0.7
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: dev.binarybush.tawk
        pluginClass: TawkPlugin
      ios:
        pluginClass: TawkPlugin
      web:
        pluginClass: TawkWeb
        fileName: tawk_web.dart
